# Generated by Django 4.0.3 on 2022-03-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_slider_alter_customer_state_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='Brand_Name',
            new_name='brand_name',
        ),
    ]
