# Generated by Django 4.0.3 on 2022-03-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_brand_name_slider_brand_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
